#!/bin/sh /etc/rc.common
# antigrayip init script

START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/antigrayip.sh

start_service() {
	config_load antigrayip
	local enabled
	config_get enabled settings enabled '1'
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "antigrayip"
}
